### ISSUE TITLE
# Module 7 

### ISSUE THREAD

**Issue by avolosiuk** [avolosiuk/mywork#3]
# Module 7

При выполнении домашнего задания 5   в классе _SortInsert_ была допущена ошибка,я задавал не правильно условия для цикла **while**  ,тем самым ловил **ArrayIndexOutOfBoundsException**
![default](https://cloud.githubusercontent.com/assets/16258520/12396901/9becfff6-be12-11e5-992f-b9304cce0cc1.png)

После еще одного разбора данного метода сортировки ,я понял ,что задаю условия для цикла   **while** не правильно,и что нужно _два условия_ объединить в один цикл  **while**
![1](https://cloud.githubusercontent.com/assets/16258520/12397012/2ac07a64-be13-11e5-9a89-239db72a7e44.png)

**Comment by aslyvets** [comment]
1. Вставлять код картинкой это не дело. Надо переделать. Можно даже сказть - это антипатрен, представь, что твой коллега захотел его скопировать, а тут на тебе :-)
2. Пожалуйста указывай прямую ссылку на решения задания в [LMS](https://app.schoology.com) , а не на весь репозиторий.

**P.S** нужно больше Маркдауна =)

**Comment by avolosiuk** [comment]
# Module 7 

При выполнении домашнего задания 5   в классе *SortInsert* была допущена ошибка,я задавал не правильно условия для цикла **while**  ,тем самым ловил **ArrayIndexOutOfBoundsException**
'  




'
 После еще одного разбора данного метода сортировки ,я понял ,что задаю условия для цикла   **while** не правильно,и что нужно *два условия* объединить в один цикл  **while**
![1](https://cloud.githubusercontent.com/assets/16258520/12397012/2ac07a64-be13-11e5-9a89-239db72a7e44.png)

**Comment by avolosiuk** [comment]
# Module 7

При выполнении домашнего задания 5   в классе _SortInsert_ была допущена ошибка,я задавал не правильно условия для цикла **while**  ,тем самым ловил **ArrayIndexOutOfBoundsException**

``` java
    int[] sortInsert(int[] Array) {
        for (int i = 1; i < Array.length; i++) {
            int x = Array[i];
            while ( Array[i - 1] > x) {
                Array[i] = Array[i - 1];
                i--;
            }
            Array[i] = x;

        }
        return Array;

    }


}
```

После еще одного разбора данного метода сортировки ,я понял ,что задаю условия для цикла   **while** не правильно,и что нужно _два условия_ `i>0` и `Array[i - 1] > x`  объединить в один цикл  **while**

``` java
  int[] sortInsert(int[] Array) {
        for ( int i = 1; i < Array.length; i++) {
            int x = Array[i];
            while (i>0 && Array[i - 1] > x) {
                Array[i] = Array[i - 1];
                i--;
            }
            Array[i] = x;

        }
        return Array;

    }
```

**Comment by aslyvets** [comment]
Вот это уже выглядит солидно, молодец! Закрывай ишью.
